from __future__ import annotations

import math
from collections.abc import Callable, Mapping
from typing import Any

from ...common import require_torch
from .config import JouleWeaveModelConfig
from .graph import (
    build_periodic_radius_graph,
    edge_vectors_from_shifts,
    normalize_cell_pbc,
    scatter_sum,
    smooth_cutoff,
)
from .layers import (
    CompactSplineBasis,
    ExpertAtomicReadout,
    MagneticMomentConstraint,
    RedoxChargeConstraint,
    SmoothFieldAttentionBlock,
)
from .physics import (
    DampedDispersion,
    ScreenedChargeEquilibration,
    ZBLRepulsion,
    dipole_from_charges,
)

torch = require_torch()
nn = torch.nn
FieldExchange = Callable[[Any, Any, Any], tuple[Any, Any, Any]]


def _graph_value(
    value: Any | None,
    *,
    graph_count: int,
    reference: Any,
    dtype: Any,
    name: str,
    default: float = 0.0,
) -> Any:
    if value is None:
        return torch.full(
            (graph_count,),
            default,
            device=reference.device,
            dtype=dtype,
        )
    if not torch.is_tensor(value):
        value = torch.as_tensor(value, device=reference.device, dtype=dtype)
    else:
        value = value.to(device=reference.device, dtype=dtype)
    value = value.reshape(-1)
    if value.numel() == 1 and graph_count > 1:
        value = value.expand(graph_count)
    if value.shape != (graph_count,):
        raise ValueError(f"{name} must be scalar or have shape [graphs]")
    return value


class JouleWeave(nn.Module):
    """JouleWeave smooth Cartesian-field neural interatomic potential.

    The local learned energy is generated by O(3)-equivariant scalar, vector, and
    symmetric rank-2 graph fields. Total energy is extensive; forces and stress are
    exact derivatives of that scalar energy. Optional ZBL, dispersion, and QEq
    terms encode known asymptotic behavior outside the densely sampled data region.
    """

    def __init__(self, config: JouleWeaveModelConfig | None = None) -> None:
        super().__init__()
        self.config = config or JouleWeaveModelConfig.universal()
        channels = self.config.hidden_dim
        self.element_embedding = nn.Embedding(
            self.config.max_atomic_number + 1,
            channels,
            padding_idx=0,
        )
        self.fidelity_embedding = nn.Embedding(
            self.config.num_fidelity_heads,
            channels,
        )
        self.condition_projection = nn.Sequential(
            nn.Linear(2, channels),
            nn.SiLU(),
            nn.Linear(channels, channels),
        )
        self.radial_basis = CompactSplineBasis(
            self.config.num_radial,
            self.config.interaction_cutoff_A,
            trainable=self.config.radial_trainable,
        )
        self.interactions = nn.ModuleList(
            SmoothFieldAttentionBlock(
                channels,
                self.config.num_radial,
                attention_heads=self.config.num_attention_heads,
                cutoff=self.config.interaction_cutoff_A,
                dropout=self.config.dropout,
                residual_scale=self.config.residual_scale,
            )
            for _ in range(self.config.num_layers)
        )
        self.readouts = nn.ModuleList(
            ExpertAtomicReadout(
                channels,
                self.config.num_experts,
                self.config.max_atomic_number,
            )
            for _ in range(self.config.num_layers)
        )
        self.magnetic_constraint = (
            MagneticMomentConstraint(
                channels,
                nonnegative=self.config.magmom_nonnegative,
                condition_scale=self.config.magmom_condition_scale,
            )
            if self.config.use_magmoms
            else None
        )
        self.redox_constraint = (
            RedoxChargeConstraint(
                channels,
                use_charges=self.config.use_charge_head,
                use_oxidation_states=self.config.use_oxidation_states,
                oxidation_state_min=self.config.oxidation_state_min,
                oxidation_state_max=self.config.oxidation_state_max,
                condition_scale=self.config.redox_condition_scale,
            )
            if self.config.use_charge_head or self.config.use_oxidation_states
            else None
        )

        references = torch.zeros(self.config.max_atomic_number + 1)
        for atomic_number, energy in self.config.atomic_reference_energies.items():
            references[int(atomic_number)] = float(energy)
        self.register_buffer("atomic_reference_eV", references)
        self.register_buffer(
            "residual_shift_eV_per_atom",
            torch.tensor(float(self.config.residual_shift_eV_per_atom)),
        )
        self.register_buffer(
            "residual_scale_eV",
            torch.tensor(float(self.config.residual_scale_eV)),
        )

        self.zbl = (
            ZBLRepulsion(
                inner_A=self.config.zbl_inner_A,
                outer_A=self.config.zbl_outer_A,
                learnable_scale=self.config.learnable_zbl_scale,
            )
            if self.config.use_zbl
            else None
        )
        self.dispersion = (
            DampedDispersion(
                self.config.max_atomic_number,
                cutoff_A=self.config.dispersion_cutoff_A,
                initial_c6_eV_A6=self.config.dispersion_init_eV_A6,
            )
            if self.config.use_dispersion
            else None
        )
        if self.config.use_qeq:
            self.qeq_head = nn.Linear(channels, 2)
            nn.init.zeros_(self.qeq_head.weight)
            nn.init.zeros_(self.qeq_head.bias)
            self.qeq = ScreenedChargeEquilibration(
                screening_A_inv=self.config.qeq_screening_A_inv,
                softening_A=self.config.qeq_softening_A,
                max_atoms=self.config.qeq_max_atoms,
            )
        else:
            self.qeq_head = None
            self.qeq = None

    @property
    def total_cutoff_A(self) -> float:
        return self.config.total_cutoff_A

    def set_energy_normalization(
        self,
        *,
        atomic_reference_energies: Mapping[int, float] | None = None,
        residual_shift_eV_per_atom: float | None = None,
        residual_scale_eV: float | None = None,
    ) -> None:
        if atomic_reference_energies is not None:
            self.atomic_reference_eV.zero_()
            cleaned: dict[int, float] = {}
            for atomic_number, energy in atomic_reference_energies.items():
                z = int(atomic_number)
                if z < 1 or z > self.config.max_atomic_number:
                    raise ValueError(f"invalid reference atomic number: {z}")
                self.atomic_reference_eV[z] = float(energy)
                cleaned[z] = float(energy)
            self.config.atomic_reference_energies = cleaned
        if residual_shift_eV_per_atom is not None:
            value = float(residual_shift_eV_per_atom)
            self.residual_shift_eV_per_atom.fill_(value)
            self.config.residual_shift_eV_per_atom = value
        if residual_scale_eV is not None:
            value = max(float(residual_scale_eV), 1.0e-8)
            self.residual_scale_eV.fill_(value)
            self.config.residual_scale_eV = value

    def _initial_fields(
        self,
        atomic_numbers: Any,
        batch: Any,
        *,
        graph_count: int,
        total_charge: Any | None,
        spin: Any | None,
        fidelity: Any | None,
    ) -> tuple[Any, Any, Any, Any, Any]:
        dtype = self.element_embedding.weight.dtype
        charge = _graph_value(
            total_charge,
            graph_count=graph_count,
            reference=atomic_numbers,
            dtype=dtype,
            name="total_charge",
        )
        spin_value = _graph_value(
            spin,
            graph_count=graph_count,
            reference=atomic_numbers,
            dtype=dtype,
            name="spin",
        )
        if fidelity is None:
            fidelity = torch.zeros(
                (graph_count,),
                device=atomic_numbers.device,
                dtype=torch.long,
            )
        elif not torch.is_tensor(fidelity):
            fidelity = torch.as_tensor(
                fidelity,
                device=atomic_numbers.device,
                dtype=torch.long,
            )
        else:
            fidelity = fidelity.to(device=atomic_numbers.device, dtype=torch.long)
        fidelity = fidelity.reshape(-1)
        if fidelity.numel() == 1 and graph_count > 1:
            fidelity = fidelity.expand(graph_count)
        if fidelity.shape != (graph_count,):
            raise ValueError("fidelity/head must be scalar or have shape [graphs]")
        if fidelity.numel() and (
            int(fidelity.min().item()) < 0
            or int(fidelity.max().item()) >= self.config.num_fidelity_heads
        ):
            raise ValueError(f"fidelity index must be in [0, {self.config.num_fidelity_heads})")

        condition = torch.stack((charge / 10.0, spin_value / 10.0), dim=-1)
        scalar = (
            self.element_embedding(atomic_numbers.long())
            + self.condition_projection(condition)[batch]
            + self.fidelity_embedding(fidelity)[batch]
        )
        vector = scalar.new_zeros((scalar.shape[0], scalar.shape[1], 3))
        tensor = scalar.new_zeros((scalar.shape[0], scalar.shape[1], 3, 3))
        return scalar, vector, tensor, charge, spin_value

    def _edge_data(
        self,
        inputs: Mapping[str, Any],
        positions: Any,
        batch: Any,
        cell: Any,
        pbc: Any,
    ) -> tuple[Any, Any, Any, Any]:
        edge_index = inputs.get("edge_index")
        if edge_index is None:
            return build_periodic_radius_graph(
                positions,
                batch,
                cell,
                pbc,
                cutoff=self.total_cutoff_A,
                max_neighbors=self.config.max_neighbors,
            )
        edge_index = edge_index.to(device=positions.device, dtype=torch.long)
        if edge_index.ndim != 2 or edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape [2, edges]")
        edge_shift = inputs.get("edge_shift")
        if edge_shift is not None:
            edge_shift = edge_shift.to(device=positions.device, dtype=torch.long)
        else:
            edge_shift = torch.zeros(
                (edge_index.shape[1], 3),
                device=positions.device,
                dtype=torch.long,
            )
        edge_vector = inputs.get("edge_vector")
        if edge_vector is None:
            edge_vector = edge_vectors_from_shifts(
                positions,
                edge_index,
                edge_shift=edge_shift,
                batch=batch,
                cell=cell,
            )
        else:
            edge_vector = edge_vector.to(device=positions.device, dtype=positions.dtype)
        if edge_vector.shape != (edge_index.shape[1], 3):
            raise ValueError("edge_vector must have shape [edges, 3]")
        edge_distance = torch.linalg.vector_norm(edge_vector, dim=-1)
        return edge_index, edge_vector, edge_distance, edge_shift

    def forward_edges(
        self,
        atomic_numbers: Any,
        edge_index: Any,
        edge_vector: Any,
        *,
        batch: Any | None = None,
        positions: Any | None = None,
        cell: Any | None = None,
        pbc: Any | None = None,
        total_charge: Any | None = None,
        spin: Any | None = None,
        fidelity: Any | None = None,
        exchange: FieldExchange | None = None,
        allow_qeq: bool = True,
    ) -> dict[str, Any]:
        """Evaluate using a precomputed directed graph.

        ``exchange`` is the domain-decomposition hook used by LAMMPS ML-IAP. It
        receives scalar/vector/tensor node fields after each interaction and must
        return fields whose ghost entries have been synchronized.
        """

        atomic_numbers = atomic_numbers.long()
        atom_count = atomic_numbers.shape[0]
        if atomic_numbers.ndim != 1:
            raise ValueError("atomic_numbers must have shape [atoms]")
        if atomic_numbers.numel() and (
            int(atomic_numbers.min().item()) < 1
            or int(atomic_numbers.max().item()) > self.config.max_atomic_number
        ):
            raise ValueError(f"atomic numbers must be in [1, {self.config.max_atomic_number}]")
        if batch is None:
            batch = torch.zeros(
                atom_count,
                device=atomic_numbers.device,
                dtype=torch.long,
            )
        else:
            batch = batch.to(device=atomic_numbers.device, dtype=torch.long)
        if batch.shape != (atom_count,):
            raise ValueError("batch must have shape [atoms]")
        graph_count = int(batch.max().item()) + 1 if batch.numel() else 1
        if edge_index.ndim != 2 or edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape [2, edges]")
        if edge_vector.shape != (edge_index.shape[1], 3):
            raise ValueError("edge_vector must have shape [edges, 3]")

        scalar, vector, tensor, charge_constraint, _spin = self._initial_fields(
            atomic_numbers,
            batch,
            graph_count=graph_count,
            total_charge=total_charge,
            spin=spin,
            fidelity=fidelity,
        )
        edge_distance = torch.linalg.vector_norm(edge_vector, dim=-1)
        interaction_mask = edge_distance < self.config.interaction_cutoff_A
        interaction_index = edge_index[:, interaction_mask]
        interaction_vector = edge_vector[interaction_mask]
        interaction_distance = edge_distance[interaction_mask]
        radial = self.radial_basis(interaction_distance)

        states: list[tuple[Any, Any, Any]] = []
        magmoms = None
        magnetic_latent = None
        redox_output: dict[str, Any] = {}
        final_interaction_index = len(self.interactions) - 1
        for layer_index, interaction in enumerate(self.interactions):
            if self.magnetic_constraint is not None and layer_index == final_interaction_index:
                scalar, magmoms, magnetic_latent = self.magnetic_constraint(
                    scalar,
                    vector,
                    tensor,
                )
            if self.redox_constraint is not None and layer_index == final_interaction_index:
                scalar, redox_output = self.redox_constraint(
                    scalar,
                    vector,
                    tensor,
                    batch,
                    charge_constraint,
                    graph_count,
                )
            scalar, vector, tensor = interaction(
                scalar,
                vector,
                tensor,
                interaction_index,
                interaction_vector,
                radial,
            )
            if exchange is not None:
                scalar, vector, tensor = exchange(scalar, vector, tensor)
            states.append((scalar, vector, tensor))

        if interaction_distance.numel():
            coordination = scatter_sum(
                smooth_cutoff(
                    interaction_distance,
                    self.config.interaction_cutoff_A,
                ),
                interaction_index[0],
                atom_count,
            )
        else:
            coordination = scalar.new_zeros((atom_count,))
        isolated_gate = -torch.expm1(-coordination)

        residual_terms: list[Any] = []
        expert_weights = None
        for readout, state in zip(self.readouts, states, strict=True):
            residual, expert_weights = readout(*state, atomic_numbers)
            residual_terms.append(residual)
        residual_energy = torch.stack(residual_terms, dim=0).sum(dim=0)
        residual_energy = residual_energy / math.sqrt(len(residual_terms))
        residual_energy = (
            residual_energy * self.residual_scale_eV + self.residual_shift_eV_per_atom
        ) * isolated_gate
        atomic_energy = self.atomic_reference_eV[atomic_numbers] + residual_energy

        receiver, sender = edge_index
        if self.zbl is not None and edge_distance.numel():
            mask = edge_distance < self.config.zbl_outer_A
            pair_energy = self.zbl(
                atomic_numbers[receiver[mask]],
                atomic_numbers[sender[mask]],
                edge_distance[mask],
            )
            atomic_energy = atomic_energy + scatter_sum(
                0.5 * pair_energy,
                receiver[mask],
                atom_count,
            )
        if self.dispersion is not None and edge_distance.numel():
            mask = edge_distance < self.config.dispersion_cutoff_A
            pair_energy = self.dispersion(
                atomic_numbers[receiver[mask]],
                atomic_numbers[sender[mask]],
                edge_distance[mask],
            )
            atomic_energy = atomic_energy + scatter_sum(
                0.5 * pair_energy,
                receiver[mask],
                atom_count,
            )

        qeq_charges = scalar.new_zeros((atom_count,))
        qeq_energy = scalar.new_zeros((graph_count,))
        qeq_dipole = scalar.new_zeros((graph_count, 3))
        if self.qeq is not None:
            if not allow_qeq:
                raise RuntimeError(
                    "JouleWeave QEq is a global graph solve and cannot be evaluated "
                    "through a domain-local edge interface"
                )
            if positions is None:
                raise ValueError("positions are required when use_qeq=True")
            qeq_values = self.qeq_head(scalar)
            electronegativity = qeq_values[:, 0]
            hardness = (
                torch.nn.functional.softplus(qeq_values[:, 1]) + self.config.qeq_min_hardness_eV
            )
            qeq_charges, qeq_atomic, qeq_energy = self.qeq(
                electronegativity,
                hardness,
                positions,
                batch,
                cell,
                pbc,
                charge_constraint,
            )
            atomic_energy = atomic_energy + qeq_atomic
            qeq_dipole = dipole_from_charges(qeq_charges, positions, batch)

        partition_charges = redox_output.get("partition_charges")
        if partition_charges is not None:
            charges = partition_charges
            if positions is None:
                dipole = scalar.new_zeros((graph_count, 3))
            else:
                dipole = dipole_from_charges(charges, positions, batch)
        else:
            charges = qeq_charges
            dipole = qeq_dipole

        total_energy = scatter_sum(atomic_energy, batch, graph_count)
        # Preserve a zero derivative for isolated systems instead of returning an
        # energy tensor disconnected from coordinates (which breaks force APIs).
        coordinate_anchor = edge_vector.sum() * 0.0
        if positions is not None:
            coordinate_anchor = coordinate_anchor + positions.sum() * 0.0
        total_energy = total_energy + coordinate_anchor
        output = {
            "energy": total_energy,
            "atomic_energies": atomic_energy,
            "charges": charges,
            "dipole": dipole,
            "qeq_charges": qeq_charges,
            "qeq_dipole": qeq_dipole,
            "qeq_energy": qeq_energy,
            "edge_index": edge_index,
            "edge_vector": edge_vector,
            "edge_distance": edge_distance,
            "coordination": coordination,
            "expert_weights": expert_weights,
            "node_scalar": scalar,
            "node_vector": vector,
            "node_tensor": tensor,
        }
        if magmoms is not None:
            output["magmoms"] = magmoms
            output["magnetic_latent"] = magnetic_latent
        for name, value in redox_output.items():
            if value is not None:
                output[name] = value
        return output

    def forward(self, inputs: Mapping[str, Any]) -> dict[str, Any]:
        atomic_numbers = inputs.get("z", inputs.get("atomic_numbers"))
        positions = inputs.get("pos", inputs.get("positions"))
        if atomic_numbers is None or positions is None:
            raise KeyError("JouleWeave requires z/atomic_numbers and pos/positions")
        atomic_numbers = atomic_numbers.to(device=positions.device, dtype=torch.long)
        batch = inputs.get("batch")
        if batch is None:
            batch = torch.zeros(
                atomic_numbers.shape[0],
                device=positions.device,
                dtype=torch.long,
            )
        else:
            batch = batch.to(device=positions.device, dtype=torch.long)
        graph_count = int(batch.max().item()) + 1 if batch.numel() else 1
        cell, pbc = normalize_cell_pbc(
            inputs.get("cell"),
            inputs.get("pbc"),
            graph_count=graph_count,
            positions=positions,
        )
        edge_index, edge_vector, _edge_distance, edge_shift = self._edge_data(
            inputs,
            positions,
            batch,
            cell,
            pbc,
        )
        output = self.forward_edges(
            atomic_numbers,
            edge_index,
            edge_vector,
            batch=batch,
            positions=positions,
            cell=cell,
            pbc=pbc,
            total_charge=inputs.get("total_charge"),
            spin=inputs.get("spin"),
            fidelity=inputs.get("fidelity", inputs.get("head")),
        )
        output["edge_shift"] = edge_shift
        return output

    def energy_and_forces(
        self,
        inputs: Mapping[str, Any],
        *,
        create_graph: bool = False,
    ) -> dict[str, Any]:
        positions = inputs.get("pos", inputs.get("positions"))
        if positions is None:
            raise KeyError("positions are required")
        if not positions.requires_grad:
            positions = positions.clone().requires_grad_(True)
            inputs = dict(inputs)
            inputs["pos"] = positions
            inputs["positions"] = positions
        output = self(inputs)
        forces = -torch.autograd.grad(
            output["energy"].sum(),
            positions,
            create_graph=create_graph,
            retain_graph=create_graph,
        )[0]
        return {**output, "forces": forces}

    def energy_forces_stress(
        self,
        inputs: Mapping[str, Any],
        *,
        create_graph: bool = False,
        compute_stress: bool = True,
    ) -> dict[str, Any]:
        positions = inputs.get("pos", inputs.get("positions"))
        atomic_numbers = inputs.get("z", inputs.get("atomic_numbers"))
        if positions is None or atomic_numbers is None:
            raise KeyError("atomic numbers and positions are required")
        if not positions.requires_grad:
            positions = positions.clone().requires_grad_(True)
        batch = inputs.get("batch")
        if batch is None:
            batch = torch.zeros(
                atomic_numbers.shape[0],
                device=positions.device,
                dtype=torch.long,
            )
        else:
            batch = batch.to(device=positions.device, dtype=torch.long)
        graph_count = int(batch.max().item()) + 1 if batch.numel() else 1
        cell, pbc = normalize_cell_pbc(
            inputs.get("cell"),
            inputs.get("pbc"),
            graph_count=graph_count,
            positions=positions,
        )

        if compute_stress:
            strain = positions.new_zeros((graph_count, 3, 3), requires_grad=True)
            deformation = (
                torch.eye(
                    3,
                    device=positions.device,
                    dtype=positions.dtype,
                )[None, :, :]
                + strain
            )
            deformed_positions = torch.einsum(
                "ni,nij->nj",
                positions,
                deformation[batch],
            )
            deformed_cell = torch.einsum("bij,bjk->bik", cell, deformation)
        else:
            strain = None
            deformed_positions = positions
            deformed_cell = cell

        evaluated_inputs = dict(inputs)
        evaluated_inputs.update(
            {
                "z": atomic_numbers,
                "atomic_numbers": atomic_numbers,
                "pos": deformed_positions,
                "positions": deformed_positions,
                "batch": batch,
                "cell": deformed_cell,
                "pbc": pbc,
            }
        )
        # Precomputed edges describe the unstrained geometry and must be rebuilt.
        for key in ("edge_index", "edge_vector", "edge_distance", "edge_shift"):
            evaluated_inputs.pop(key, None)
        output = self(evaluated_inputs)
        differentiation_inputs = [positions]
        if strain is not None:
            differentiation_inputs.append(strain)
        gradients = torch.autograd.grad(
            output["energy"].sum(),
            differentiation_inputs,
            create_graph=create_graph,
            retain_graph=create_graph,
        )
        result = {**output, "forces": -gradients[0]}
        if strain is not None:
            volume = torch.abs(torch.det(cell))
            periodic = torch.any(pbc, dim=-1)
            if bool(torch.any(periodic & (volume < 1.0e-12)).item()):
                raise ValueError("periodic stress requires a non-singular cell")
            safe_volume = torch.where(periodic, volume, torch.ones_like(volume))
            stress_matrix = 0.5 * (gradients[1] + gradients[1].transpose(-1, -2))
            stress_matrix = stress_matrix / safe_volume[:, None, None]
            stress_matrix = stress_matrix * periodic[:, None, None].to(stress_matrix.dtype)
            result["stress"] = stress_matrix[
                :,
                [0, 1, 2, 1, 0, 0],
                [0, 1, 2, 2, 2, 1],
            ]
        return result


__all__ = ["JouleWeave"]
