from __future__ import annotations

from pathlib import Path

import numpy as np

from zynnova.zynmorph import (
    GenerationConfig,
    MicrostructureCondition,
    MicrostructureVolume,
    export_comsol_mphtxt,
    export_voxel_comsol_mphtxt,
    inspect_comsol_mphtxt,
    mesh_microstructure,
    run_zynmorph,
)


def _last_mesh_coordinate(path: Path) -> np.ndarray:
    lines = path.read_text(encoding="utf-8").splitlines()
    marker = lines.index("# Mesh vertex coordinates")
    count_line = next(
        line for line in reversed(lines[:marker]) if "# number of mesh vertices" in line
    )
    count = int(count_line.split()[0])
    coordinates = lines[marker + 1 : marker + 1 + count]
    return np.fromstring(coordinates[-1], sep=" ")


def test_tet4_mphtxt_reuses_native_writer_and_preserves_selections(tmp_path) -> None:
    labels = np.asarray(
        [
            [[10, 10, 4], [3, 8, 4], [3, 4, 4]],
            [[10, 3, 4], [3, 9, 4], [3, 4, 4]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[2, 2, 1], [2, 7, 1], [2, 1, 11]],
        ],
        dtype=np.int32,
    )
    volume = MicrostructureVolume(
        labels=labels,
        voxel_size_m=(80e-9, 110e-9, 140e-9),
        origin_m=(1e-6, 2e-6, 3e-6),
    )
    fem = mesh_microstructure(volume, maximum_tetrahedra=10_000, method="structured")
    target = tmp_path / "complex_tet4.mphtxt"
    report = export_comsol_mphtxt(
        target,
        fem.mesh,
        domain_selections={
            "electrochemically_active": (1, 3),
            "electron_conducting": (1, 3, 10, 11),
        },
    )
    info = inspect_comsol_mphtxt(target)

    assert target.is_file()
    assert target.read_text(encoding="utf-8").startswith(
        "# COMSOL native text mesh generated by ZynNova ZynSim\n"
    )
    assert info.format_version == (0, 1)
    assert info.mesh_class_version == 4
    assert info.start_vertex_index == 0
    assert info.vertex_count == fem.mesh.n_nodes == report.vertex_count
    assert info.element_counts["tet"] == fem.mesh.n_cells == report.tetrahedron_count
    assert info.element_counts["tri"] == report.triangle_count
    assert report.region_entity_map == {
        region: index
        for index, region in enumerate(sorted(np.unique(labels)), start=1)
    }

    selections = {(item.label, item.dimension) for item in info.selections}
    for label in (
        "all_domains",
        "all_electrolyte",
        "all_active_material",
        "all_interphases",
        "all_cracks_and_voids",
        "all_current_collectors",
        "electrochemically_active",
        "electron_conducting",
    ):
        assert (label, 3) in selections
    for label in (
        "xmin",
        "xmax",
        "ymin",
        "ymax",
        "zmin",
        "zmax",
        "all_exterior",
        "x_terminal_pair",
        "transverse_boundaries",
    ):
        assert (label, 2) in selections
    assert any(label.startswith("interface_") and dim == 2 for label, dim in selections)


def test_out_of_core_voxel_mphtxt_preserves_zynmorph_zyx_physical_axes(tmp_path) -> None:
    labels = np.zeros((2, 3, 4), dtype=np.int32)  # z, y, x
    labels[:, :, 2:] = 1
    volume = MicrostructureVolume(
        labels=labels,
        voxel_size_m=(2.0, 3.0, 5.0),  # dz, dy, dx
        origin_m=(7.0, 11.0, 13.0),  # oz, oy, ox
        phase_names={0: "pore_electrolyte", 1: "active_material"},
    )
    target = tmp_path / "streamed_hex8.mphtxt"
    report = export_voxel_comsol_mphtxt(
        target,
        volume,
        element_type="hex8",
        prefer_native=False,
        chunk_size=5,
    )
    info = inspect_comsol_mphtxt(target)

    assert report.out_of_core
    assert info.vertex_count == (4 + 1) * (3 + 1) * (2 + 1)
    assert info.element_counts["hex"] == labels.size
    assert np.allclose(_last_mesh_coordinate(target), (33.0, 20.0, 11.0))
    selections = {(item.label, item.dimension) for item in info.selections}
    assert ("pore_electrolyte", 3) in selections
    assert ("active_material", 3) in selections
    assert ("xmin", 2) in selections
    assert ("interface_pore_electrolyte_active_material", 2) in selections


def test_zynmorph_pipeline_accepts_mphtxt_alias_and_registers_artifact(tmp_path) -> None:
    condition = MicrostructureCondition(
        shape=(3, 4, 5),
        phase_fractions={1: 0.45, 2: 0.40, 5: 0.15},
        voxel_size_m=(90e-9, 100e-9, 120e-9),
        percolation_axes={1: (2,), 2: (2,)},
        seed=77,
    )
    config = GenerationConfig(
        backend="spectral-exact",
        mesh_backend="structured",
        output_directory=str(tmp_path / "runs"),
        export_volume_formats=("npz",),
        export_mesh_formats=("comsol",),
        maximum_tetrahedra=10_000,
    )
    assert config.export_mesh_formats == ("mphtxt",)
    run = run_zynmorph(condition, config)
    assert run.artifacts["mesh-mphtxt"].is_file()
    info = inspect_comsol_mphtxt(run.artifacts["mesh-mphtxt"])
    assert info.element_counts["tet"] == condition.n_voxels * 6


def test_compact_tet4_mphtxt_without_explicit_lower_dimensional_elements(tmp_path) -> None:
    volume = MicrostructureVolume(
        labels=np.asarray([[[1, 2]], [[1, 2]]], dtype=np.int32),
        voxel_size_m=1.0e-7,
    )
    fem = mesh_microstructure(volume, maximum_tetrahedra=100, method="structured")
    target = tmp_path / "compact.mphtxt"
    report = export_comsol_mphtxt(
        target,
        fem.mesh,
        include_boundaries=False,
        include_coordinate_boundaries=False,
        include_default_boundary_unions=False,
    )
    info = inspect_comsol_mphtxt(target)
    assert report.triangle_count == 0
    assert info.element_counts == {"tet": fem.mesh.n_cells}
