"""Dimension-aware neural-symbolic learning for polymer physics."""

from __future__ import annotations

from .backends import (
    BACKENDS,
    NativeSymbolicBackend,
    PSEBackend,
    PhyE2EBackend,
    PhySOBackend,
    PySRBackend,
    SymbolicProblem,
    create_backend,
)
from .config import (
    OracleBackendName,
    PhysicsLearningConfig,
    SymbolicBackendName,
)
from .dimensions import (
    CONDUCTIVITY,
    CURRENT,
    DIFFUSIVITY,
    DIMENSIONLESS,
    DIPOLE,
    ELECTRIC_FIELD,
    ENERGY,
    FREQUENCY,
    LENGTH,
    MASS,
    PIEZOELECTRIC_D,
    POLARIZATION,
    PRESSURE,
    SI_BASES,
    TEMPERATURE,
    TIME,
    PhysicalDimension,
    VariableSpec,
    buckingham_pi_groups,
    infer_variable_spec,
    resolve_variable_specs,
)
from .dynamics import SparseDynamicsDiscoverer, discover_sparse_dynamics
from .engine import PhysicsLearningEngine, discover_physical_laws
from .interaction import HessianInteractionDecomposer, QuadraticInteractionOracle
from .neural import KANOracleDiagnostics, PhysicsKANOracle
from .schema import (
    BackendStatus,
    DimensionlessGroup,
    DynamicsDiscoveryReport,
    DynamicsEquation,
    InteractionDecomposition,
    InteractionEdge,
    PhysicsEquation,
    PhysicsLearningReport,
    dynamics_discovery_report_from_dict,
    physics_learning_report_from_dict,
)


__all__ = [
    "BACKENDS",
    "BackendStatus",
    "CONDUCTIVITY",
    "CURRENT",
    "DIFFUSIVITY",
    "DIMENSIONLESS",
    "DIPOLE",
    "DimensionlessGroup",
    "DynamicsDiscoveryReport",
    "DynamicsEquation",
    "ELECTRIC_FIELD",
    "ENERGY",
    "FREQUENCY",
    "HessianInteractionDecomposer",
    "InteractionDecomposition",
    "InteractionEdge",
    "KANOracleDiagnostics",
    "LENGTH",
    "MASS",
    "NativeSymbolicBackend",
    "OracleBackendName",
    "PIEZOELECTRIC_D",
    "POLARIZATION",
    "PRESSURE",
    "PSEBackend",
    "PhyE2EBackend",
    "PhySOBackend",
    "PhysicalDimension",
    "PhysicsEquation",
    "PhysicsKANOracle",
    "PhysicsLearningConfig",
    "PhysicsLearningEngine",
    "PhysicsLearningReport",
    "PySRBackend",
    "QuadraticInteractionOracle",
    "SI_BASES",
    "SparseDynamicsDiscoverer",
    "SymbolicBackendName",
    "SymbolicProblem",
    "TEMPERATURE",
    "TIME",
    "VariableSpec",
    "buckingham_pi_groups",
    "create_backend",
    "discover_physical_laws",
    "discover_sparse_dynamics",
    "dynamics_discovery_report_from_dict",
    "infer_variable_spec",
    "physics_learning_report_from_dict",
    "resolve_variable_specs",
]
