#pragma once

#include <Kokkos_Core.hpp>

#include <cstddef>
#include <cstdint>

namespace zynnova::zivar {

using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using ScalarView = Kokkos::View<double*, ExecutionSpace>;
using IndexView = Kokkos::View<std::int32_t*, ExecutionSpace>;

// Matrix-free symmetric operator
//
//   (A x)_i = onsite_i x_i + sum_{(i,j) in edges} coupling_ij x_j.
//
// Each off-diagonal edge is stored exactly once with edge_i < edge_j.  The
// reverse contribution is generated by the Kokkos kernel, so no CSR transpose
// or dense N x N storage is required.
class SymmetricSparseOperator {
public:
    SymmetricSparseOperator(std::size_t atom_count, std::size_t edge_count);

    [[nodiscard]] std::size_t atom_count() const noexcept;
    [[nodiscard]] std::size_t edge_count() const noexcept;

    [[nodiscard]] ScalarView& onsite() noexcept;
    [[nodiscard]] const ScalarView& onsite() const noexcept;
    [[nodiscard]] IndexView& edge_i() noexcept;
    [[nodiscard]] const IndexView& edge_i() const noexcept;
    [[nodiscard]] IndexView& edge_j() noexcept;
    [[nodiscard]] const IndexView& edge_j() const noexcept;
    [[nodiscard]] ScalarView& coupling() noexcept;
    [[nodiscard]] const ScalarView& coupling() const noexcept;

private:
    std::size_t atom_count_{};
    std::size_t edge_count_{};
    ScalarView onsite_;
    IndexView edge_i_;
    IndexView edge_j_;
    ScalarView coupling_;
};

// y <- A x.  The off-diagonal edge loop uses device-side atomics so the same
// implementation runs on serial, threaded CPU, HIP, and CUDA execution spaces.
void apply_operator(
    const SymmetricSparseOperator& matrix,
    const ScalarView& x,
    const ScalarView& y
);

[[nodiscard]] double dot(const ScalarView& left, const ScalarView& right);
[[nodiscard]] double l2_norm(const ScalarView& values);

// y <- alpha x + beta y.
void axpby(
    double alpha,
    const ScalarView& x,
    double beta,
    const ScalarView& y
);

// z <- diag(A)^{-1} r.  Callers must provide a strictly positive onsite
// diagonal; pcg_solve validates this condition before launching this kernel.
void apply_jacobi_preconditioner(
    const SymmetricSparseOperator& matrix,
    const ScalarView& residual,
    const ScalarView& preconditioned
);

// sum(values) - target.  This is the observable equality-constraint residual
// used by charge-constrained QEq/SCF callers.
[[nodiscard]] double total_constraint_residual(
    const ScalarView& values,
    double target
);

// Orthogonally project values onto sum(values) = target.
void project_to_total(const ScalarView& values, double target);

enum class PcgTermination {
    converged,
    maximum_iterations,
    non_positive_curvature,
    invalid_preconditioner,
    non_finite_residual,
};

struct PcgOptions {
    double absolute_tolerance{1.0e-12};
    double relative_tolerance{1.0e-10};
    double minimum_curvature{1.0e-30};
    int maximum_iterations{500};
    bool use_jacobi_preconditioner{true};
};

struct PcgReport {
    PcgTermination termination{PcgTermination::maximum_iterations};
    bool converged{false};
    int iterations{0};
    double rhs_norm{0.0};
    double initial_residual_norm{0.0};
    double residual_norm{0.0};
};

// Solve A x = rhs for a symmetric positive-definite operator.  This primitive
// intentionally does not hide failures: non-positive curvature, an invalid
// Jacobi diagonal, non-finite residuals, and iteration exhaustion have distinct
// termination states.
[[nodiscard]] PcgReport pcg_solve(
    const SymmetricSparseOperator& matrix,
    const ScalarView& rhs,
    const ScalarView& solution,
    const PcgOptions& options = {}
);

[[nodiscard]] const char* termination_name(PcgTermination termination) noexcept;

}  // namespace zynnova::zivar
