"""Auditable geometry exporters with optional meshio/trimesh/Blender bridges."""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, Mapping

import numpy as np

from ..core.exceptions import BackendUnavailableError, GeometryError
from ..core.process import run_process
from ..core.serialization import dump_json
from .types import PointCloud, TriangleMesh, VolumeMesh


def export_point_cloud(path: str | Path, cloud: PointCloud) -> Path:
    target = Path(path)
    suffix = target.suffix.lower()
    if suffix == ".ply":
        return _write_point_ply(target, cloud)
    if suffix == ".npz":
        target.parent.mkdir(parents=True, exist_ok=True)
        payload: dict[str, np.ndarray] = {"points": cloud.points}
        if cloud.colors is not None:
            payload["colors"] = cloud.colors
        if cloud.normals is not None:
            payload["normals"] = cloud.normals
        if cloud.confidence is not None:
            payload["confidence"] = cloud.confidence
        np.savez_compressed(target, **payload)
        return target
    raise GeometryError(f"unsupported point-cloud format {suffix!r}; use .ply or .npz")


def export_triangle_mesh(
    path: str | Path,
    mesh: TriangleMesh,
    *,
    binary: bool = False,
) -> Path:
    target = Path(path)
    suffix = target.suffix.lower()
    if suffix == ".obj":
        return _write_obj(target, mesh)
    if suffix == ".ply":
        return _write_mesh_ply(target, mesh)
    if suffix == ".stl":
        return _write_stl(target, mesh)
    if suffix == ".npz":
        target.parent.mkdir(parents=True, exist_ok=True)
        payload = {"vertices": mesh.vertices, "faces": mesh.faces}
        if mesh.vertex_colors is not None:
            payload["vertex_colors"] = mesh.vertex_colors
        if mesh.vertex_normals is not None:
            payload["vertex_normals"] = mesh.vertex_normals
        if mesh.uv is not None:
            payload["uv"] = mesh.uv
        if mesh.face_materials is not None:
            payload["face_materials"] = mesh.face_materials
        np.savez_compressed(target, **payload)
        return target
    if suffix in {".glb", ".gltf"}:
        return _write_with_trimesh(target, mesh)
    if suffix in {".fbx", ".usd", ".usda", ".usdc", ".abc", ".dae"}:
        return _write_with_blender(target, mesh)
    return _write_with_meshio(target, mesh, binary=binary)


def export_volume_mesh(
    path: str | Path,
    mesh: VolumeMesh,
    *,
    binary: bool = False,
) -> Path:
    target = Path(path)
    suffix = target.suffix.lower()
    if suffix == ".vtk":
        return _write_vtk(target, mesh)
    if suffix == ".msh":
        return _write_gmsh22(target, mesh)
    if suffix == ".inp":
        return _write_abaqus(target, mesh)
    if suffix == ".npz":
        target.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            target,
            nodes=mesh.nodes,
            tetrahedra=mesh.tetrahedra,
            cell_regions=mesh.cell_regions,
        )
        dump_json(target.with_suffix(".regions.json"), mesh.region_names)
        return target
    return _write_volume_with_meshio(target, mesh, binary=binary)


def _write_obj(path: Path, mesh: TriangleMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# ZynNova OBJ\n"]
    for vertex in mesh.vertices:
        lines.append(f"v {vertex[0]:.17g} {vertex[1]:.17g} {vertex[2]:.17g}\n")
    if mesh.uv is not None:
        for uv in mesh.uv:
            lines.append(f"vt {uv[0]:.17g} {uv[1]:.17g}\n")
    for face in mesh.faces + 1:
        if mesh.uv is None:
            lines.append(f"f {face[0]} {face[1]} {face[2]}\n")
        else:
            lines.append(
                f"f {face[0]}/{face[0]} {face[1]}/{face[1]} {face[2]}/{face[2]}\n"
            )
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _write_mesh_ply(path: Path, mesh: TriangleMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    has_color = mesh.vertex_colors is not None
    header = [
        "ply\n",
        "format ascii 1.0\n",
        "comment generated by ZynNova\n",
        f"element vertex {mesh.n_vertices}\n",
        "property double x\nproperty double y\nproperty double z\n",
    ]
    if has_color:
        header.append("property uchar red\nproperty uchar green\nproperty uchar blue\n")
    header.extend(
        [
            f"element face {mesh.n_faces}\n",
            "property list uchar int vertex_indices\n",
            "end_header\n",
        ]
    )
    lines = header
    colors = None
    if has_color:
        assert mesh.vertex_colors is not None
        colors = np.clip(np.rint(mesh.vertex_colors * 255.0), 0, 255).astype(np.uint8)
    for index, vertex in enumerate(mesh.vertices):
        line = f"{vertex[0]:.17g} {vertex[1]:.17g} {vertex[2]:.17g}"
        if colors is not None:
            line += f" {colors[index, 0]} {colors[index, 1]} {colors[index, 2]}"
        lines.append(line + "\n")
    for face in mesh.faces:
        lines.append(f"3 {face[0]} {face[1]} {face[2]}\n")
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _write_point_ply(path: Path, cloud: PointCloud) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    has_color = cloud.colors is not None
    header = [
        "ply\nformat ascii 1.0\ncomment generated by ZynNova\n",
        f"element vertex {cloud.n_points}\n",
        "property double x\nproperty double y\nproperty double z\n",
    ]
    if has_color:
        header.append("property uchar red\nproperty uchar green\nproperty uchar blue\n")
    if cloud.confidence is not None:
        header.append("property float confidence\n")
    header.append("end_header\n")
    lines = header
    colors = None
    if has_color:
        assert cloud.colors is not None
        colors = np.clip(np.rint(cloud.colors * 255.0), 0, 255).astype(np.uint8)
    for index, point in enumerate(cloud.points):
        line = f"{point[0]:.17g} {point[1]:.17g} {point[2]:.17g}"
        if colors is not None:
            line += f" {colors[index, 0]} {colors[index, 1]} {colors[index, 2]}"
        if cloud.confidence is not None:
            line += f" {cloud.confidence[index]:.9g}"
        lines.append(line + "\n")
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _write_stl(path: Path, mesh: TriangleMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    triangles = mesh.vertices[mesh.faces]
    normals = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
    lengths = np.linalg.norm(normals, axis=1)
    normals = np.divide(normals, lengths[:, None], out=np.zeros_like(normals), where=lengths[:, None] > 0)
    with path.open("w", encoding="ascii") as stream:
        stream.write("solid zynnova\n")
        for normal, triangle in zip(normals, triangles, strict=True):
            stream.write(f"  facet normal {normal[0]:.9g} {normal[1]:.9g} {normal[2]:.9g}\n")
            stream.write("    outer loop\n")
            for vertex in triangle:
                stream.write(f"      vertex {vertex[0]:.17g} {vertex[1]:.17g} {vertex[2]:.17g}\n")
            stream.write("    endloop\n  endfacet\n")
        stream.write("endsolid zynnova\n")
    return path


def _write_vtk(path: Path, mesh: VolumeMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii") as stream:
        stream.write("# vtk DataFile Version 3.0\nZynNova Tet4 mesh\nASCII\nDATASET UNSTRUCTURED_GRID\n")
        stream.write(f"POINTS {mesh.n_nodes} double\n")
        np.savetxt(stream, mesh.nodes, fmt="%.17g")
        stream.write(f"CELLS {mesh.n_cells} {mesh.n_cells * 5}\n")
        cells = np.column_stack((np.full(mesh.n_cells, 4, dtype=np.int64), mesh.tetrahedra))
        np.savetxt(stream, cells, fmt="%d")
        stream.write(f"CELL_TYPES {mesh.n_cells}\n")
        np.savetxt(stream, np.full(mesh.n_cells, 10, dtype=np.int64), fmt="%d")
        stream.write(f"CELL_DATA {mesh.n_cells}\nSCALARS region int 1\nLOOKUP_TABLE default\n")
        np.savetxt(stream, mesh.cell_regions, fmt="%d")
    return path


def _write_gmsh22(path: Path, mesh: VolumeMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii") as stream:
        stream.write("$MeshFormat\n2.2 0 8\n$EndMeshFormat\n")
        stream.write(f"$Nodes\n{mesh.n_nodes}\n")
        for index, node in enumerate(mesh.nodes, start=1):
            stream.write(f"{index} {node[0]:.17g} {node[1]:.17g} {node[2]:.17g}\n")
        stream.write("$EndNodes\n")
        stream.write(f"$Elements\n{mesh.n_cells}\n")
        for index, (tetra, region) in enumerate(
            zip(mesh.tetrahedra, mesh.cell_regions, strict=True),
            start=1,
        ):
            nodes = tetra + 1
            tag = int(region)
            stream.write(
                f"{index} 4 2 {tag} {tag} {nodes[0]} {nodes[1]} {nodes[2]} {nodes[3]}\n"
            )
        stream.write("$EndElements\n")
    return path


def _write_abaqus(path: Path, mesh: VolumeMesh) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii") as stream:
        stream.write("*Heading\n** ZynNova generated Tet4 mesh\n*Node\n")
        for index, node in enumerate(mesh.nodes, start=1):
            stream.write(f"{index}, {node[0]:.17g}, {node[1]:.17g}, {node[2]:.17g}\n")
        stream.write("*Element, type=C3D4\n")
        for index, tetra in enumerate(mesh.tetrahedra + 1, start=1):
            stream.write(f"{index}, {tetra[0]}, {tetra[1]}, {tetra[2]}, {tetra[3]}\n")
        for region in np.unique(mesh.cell_regions):
            cell_ids = np.flatnonzero(mesh.cell_regions == region) + 1
            name = _safe_set_name(mesh.region_names.get(int(region), f"REGION_{int(region)}"))
            stream.write(f"*Elset, elset={name}\n")
            for start in range(0, len(cell_ids), 16):
                stream.write(", ".join(str(value) for value in cell_ids[start : start + 16]) + "\n")
    return path


def _write_with_trimesh(path: Path, mesh: TriangleMesh) -> Path:
    try:
        import trimesh
    except ImportError as exc:
        raise BackendUnavailableError(
            "GLB/glTF export requires trimesh; install zynnova[zynnova-geometry]"
        ) from exc
    path.parent.mkdir(parents=True, exist_ok=True)
    visual = None
    if mesh.vertex_colors is not None:
        colors = np.column_stack(
            (
                np.clip(np.rint(mesh.vertex_colors * 255.0), 0, 255).astype(np.uint8),
                np.full(mesh.n_vertices, 255, dtype=np.uint8),
            )
        )
        visual = trimesh.visual.ColorVisuals(vertex_colors=colors)
    value = trimesh.Trimesh(
        vertices=mesh.vertices,
        faces=mesh.faces,
        vertex_normals=mesh.vertex_normals,
        visual=visual,
        process=False,
    )
    value.export(path)
    return path


def _write_with_meshio(path: Path, mesh: TriangleMesh, *, binary: bool) -> Path:
    try:
        import meshio
    except ImportError as exc:
        raise GeometryError(
            f"unsupported mesh format {path.suffix!r}; install meshio for extended export"
        ) from exc
    path.parent.mkdir(parents=True, exist_ok=True)
    kwargs: dict[str, Any] = {}
    if path.suffix.lower() not in {".obj", ".stl"}:
        kwargs["binary"] = binary
    meshio.write(path, meshio.Mesh(points=mesh.vertices, cells=[("triangle", mesh.faces)]), **kwargs)
    return path


def _write_volume_with_meshio(path: Path, mesh: VolumeMesh, *, binary: bool) -> Path:
    try:
        import meshio
    except ImportError as exc:
        raise GeometryError(
            f"unsupported volume format {path.suffix!r}; install meshio for extended export"
        ) from exc
    path.parent.mkdir(parents=True, exist_ok=True)
    meshio.write(
        path,
        meshio.Mesh(
            points=mesh.nodes,
            cells=[("tetra", mesh.tetrahedra)],
            cell_data={"region": [mesh.cell_regions]},
        ),
        binary=binary,
    )
    return path


def _write_with_blender(path: Path, mesh: TriangleMesh) -> Path:
    blender = shutil.which("blender")
    if blender is None:
        raise BackendUnavailableError(
            f"{path.suffix} export requires Blender on PATH; OBJ/PLY/STL/GLB work without it"
        )
    staging = path.with_suffix(".staging.obj")
    _write_obj(staging, mesh)
    script = path.with_suffix(".export.py")
    script.write_text(_blender_export_script(staging, path), encoding="utf-8")
    try:
        run_process([blender, "--background", "--python", str(script)])
    finally:
        staging.unlink(missing_ok=True)
        script.unlink(missing_ok=True)
    if not path.is_file():
        raise GeometryError(f"Blender completed but did not create {path}")
    return path


def _blender_export_script(source: Path, target: Path) -> str:
    suffix = target.suffix.lower()
    export = {
        ".fbx": f"bpy.ops.export_scene.fbx(filepath={str(target)!r})",
        ".abc": f"bpy.ops.wm.alembic_export(filepath={str(target)!r})",
        ".dae": f"bpy.ops.wm.collada_export(filepath={str(target)!r})",
        ".usd": f"bpy.ops.wm.usd_export(filepath={str(target)!r})",
        ".usda": f"bpy.ops.wm.usd_export(filepath={str(target)!r})",
        ".usdc": f"bpy.ops.wm.usd_export(filepath={str(target)!r})",
    }.get(suffix)
    if export is None:
        raise GeometryError(f"Blender bridge does not support {suffix}")
    return (
        "import bpy\n"
        "bpy.ops.object.select_all(action='SELECT')\n"
        "bpy.ops.object.delete(use_global=False)\n"
        f"bpy.ops.wm.obj_import(filepath={str(source)!r})\n"
        f"{export}\n"
    )


def _safe_set_name(name: str) -> str:
    cleaned = "".join(character if character.isalnum() else "_" for character in name.upper())
    return cleaned[:80] or "REGION"


def write_export_manifest(
    path: str | Path,
    *,
    outputs: Mapping[str, str | Path],
    metadata: Mapping[str, Any] | None = None,
) -> Path:
    payload = {
        "outputs": {name: str(Path(value).resolve()) for name, value in outputs.items()},
        "metadata": dict(metadata or {}),
    }
    return dump_json(path, payload)


__all__ = [
    "export_point_cloud",
    "export_triangle_mesh",
    "export_volume_mesh",
    "write_export_manifest",
]
